[package]
name = "mpwm"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penrose = "0.3.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

